# Generated by Django 5.1.6 on 2025-02-15 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employers', '0002_address_latitude_address_longitude'),
        ('territories', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='territoryliaison',
            name='territory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='territories.territory'),
        ),
        migrations.AlterField(
            model_name='employer',
            name='territory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='territories.territory'),
        ),
        migrations.DeleteModel(
            name='Territory',
        ),
    ]
