# Generated by Django 5.1.6 on 2025-02-15 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employers', '0004_employee_distance_from_site_cycling_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='distance_from_site_cycling',
            new_name='cycling_distance_from_site',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='distance_from_site_direct',
            new_name='direct_distance_from_site',
        ),
        migrations.AddField(
            model_name='employee',
            name='route_polyline_from_site',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='route_polyline_to_site',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
